// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  return {
    routes: {"agreement":{"path":"agreement","id":"agreement","parentId":"@@/global-layout","file":"agreement.tsx"},"children":{"path":"children","id":"children","parentId":"@@/global-layout","file":"children.tsx"},"index":{"path":"/","id":"index","parentId":"@@/global-layout","file":"index.tsx"},"docs":{"path":"docs","id":"docs","parentId":"@@/global-layout","file":"docs.tsx"},"@@/global-layout":{"id":"@@/global-layout","path":"/","file":"@/layouts/index.tsx","isLayout":true}},
    routeComponents: {
'agreement': React.lazy(() => import(/* webpackChunkName: "src__pages__agreement" */'../../../src/pages/agreement.tsx')),
'children': React.lazy(() => import(/* webpackChunkName: "src__pages__children" */'../../../src/pages/children.tsx')),
'index': React.lazy(() => import(/* webpackChunkName: "src__pages__index" */'../../../src/pages/index.tsx')),
'docs': React.lazy(() => import(/* webpackChunkName: "src__pages__docs" */'../../../src/pages/docs.tsx')),
'@@/global-layout': React.lazy(() => import(/* webpackChunkName: "layouts__index" */'@/layouts/index.tsx')),
},
  };
}
